// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartRoom.API.Data;

#nullable disable

namespace SmartRoom.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316065750_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartRoom.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SmartRoom.API.Models.BookingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingLogs");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            Name = "Gedung D4"
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            Name = "Gedung D3"
                        },
                        new
                        {
                            Id = 3,
                            CampusId = 1,
                            Name = "SAW"
                        },
                        new
                        {
                            Id = 4,
                            CampusId = 1,
                            Name = "Pascasarjana"
                        });
                });

            modelBuilder.Entity("SmartRoom.API.Models.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminRegistrationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberRegistrationToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Campuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminRegistrationToken = "ADM-123",
                            MemberRegistrationToken = "MBR-123",
                            Name = "Politeknik Elektronika Negeri Surabaya"
                        });
                });

            modelBuilder.Entity("SmartRoom.API.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CampusId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            CampusId = 1,
                            Capacity = 60,
                            IsAvailable = true,
                            RoomName = "C303",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 2,
                            CampusId = 1,
                            Capacity = 30,
                            IsAvailable = true,
                            RoomName = "HH106",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 3,
                            CampusId = 1,
                            Capacity = 120,
                            IsAvailable = true,
                            RoomName = "SAW 0708",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 4,
                            CampusId = 1,
                            Capacity = 300,
                            IsAvailable = true,
                            RoomName = "Auditorium 501",
                            RoomTypeId = 4
                        });
                });

            modelBuilder.Entity("SmartRoom.API.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampusId = 1,
                            Name = "Classroom"
                        },
                        new
                        {
                            Id = 2,
                            CampusId = 1,
                            Name = "Laboratory"
                        },
                        new
                        {
                            Id = 3,
                            CampusId = 1,
                            Name = "Meeting Room"
                        },
                        new
                        {
                            Id = 4,
                            CampusId = 1,
                            Name = "Auditorium"
                        });
                });

            modelBuilder.Entity("SmartRoom.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "superadmin@smartroom.com",
                            Password = "$2a$11$1Wl1cZhn9umGlooYvlmTauykm5WEgpcCE9pjRqEzrSas8St/o6EcW",
                            Role = "SuperAdmin",
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("SmartRoom.API.Models.Booking", b =>
                {
                    b.HasOne("SmartRoom.API.Models.Campus", "Campus")
                        .WithMany("Bookings")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRoom.API.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRoom.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRoom.API.Models.BookingLog", b =>
                {
                    b.HasOne("SmartRoom.API.Models.Booking", "Booking")
                        .WithMany("Logs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Building", b =>
                {
                    b.HasOne("SmartRoom.API.Models.Campus", "Campus")
                        .WithMany("Buildings")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Room", b =>
                {
                    b.HasOne("SmartRoom.API.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRoom.API.Models.Campus", "Campus")
                        .WithMany("Rooms")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRoom.API.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Campus");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("SmartRoom.API.Models.RoomType", b =>
                {
                    b.HasOne("SmartRoom.API.Models.Campus", "Campus")
                        .WithMany("RoomTypes")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("SmartRoom.API.Models.User", b =>
                {
                    b.HasOne("SmartRoom.API.Models.Campus", "Campus")
                        .WithMany("Users")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Booking", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Campus", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Buildings");

                    b.Navigation("RoomTypes");

                    b.Navigation("Rooms");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SmartRoom.API.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SmartRoom.API.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SmartRoom.API.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
